### ISSUE TITLE
Feature - recursive

### ISSUE THREAD

**Issue by danielgomezrico** [subzey/zopfli-png#10]
Allow it to run over a folder and optimize every png that finds with `-R` or something

**Comment by subzey** [comment]
OMG, someone still use this stuff!

I'm certainly proud that my ugly solution was the first implementation of zopfli applied to PNGs. But it's eh... ugly. And currently there are many other, much better projects, most notably [official Google's zopflipng](https://github.com/google/zopfli/blob/master/README.zopflipng). I'd like to encourage you to use it instead, it's native and fast and tested.

**Comment by subzey** [comment]
Closing the issue: This abandonware is about to be archived
