### ISSUE TITLE
Create npm package

### ISSUE THREAD

**Issue by ai** [subzey/zopfli-png#3]
You need to add `package.json` with your dependencies (after it you can remove `node_modules` from repo, dependencies will install automaticaly by `npm install`.

In `package.json` you can set your binary. After it, you need to publish you npm `zopfi-png` package, and your user can very easy install your probgramm by npm:

``` sh
npm install --global zopfi-png
zopfi-png icon.png
```

Not I can't install your cool tool, because I don't like to install any packages in user spaces without package manager.

**Comment by subzey** [comment]
Closing the issue: This abandonware is about to be archived.

https://sourceforge.net/projects/apng/files/APNG_Optimizer/ can be used to recompress APNGs
